from pathlib import Path
from tempfile import TemporaryDirectory
import json
import re
import unittest

from tools.patch_web_export import DEFAULT_SITE_URL, STATIC_DIR, load_site_config, patch

SHELL = """<!DOCTYPE html><html lang="en"><head><title>World Fight</title></head><body><canvas id="canvas"></canvas>
<div id="status"><progress id="status-progress"></progress><div id="status-notice"></div></div>
<script src="index.js"></script></body></html>"""

CONFIG = {"goatcounter_code": "", "linkedin_url": "https://www.linkedin.com/in/roee-angel/", "site_url": DEFAULT_SITE_URL}


class SeoShellTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.folder = TemporaryDirectory()
        cls.out = Path(cls.folder.name)
        (cls.out / "index.html").write_text(SHELL, encoding="utf-8")
        patch(cls.out / "index.html", CONFIG)
        cls.page = (cls.out / "index.html").read_text(encoding="utf-8")

    @classmethod
    def tearDownClass(cls):
        cls.folder.cleanup()

    def test_single_hebrew_title_description_and_canonical(self):
        self.assertEqual(self.page.count("<title>"), 1)
        self.assertIn('<html lang="he"', self.page)
        title = re.search(r"<title>(.*?)</title>", self.page).group(1)
        self.assertIn("World Fight", title)
        self.assertLessEqual(len(title), 80)
        desc = re.search(r'<meta name="description" content="([^"]+)"', self.page).group(1)
        self.assertTrue(70 <= len(desc) <= 200, len(desc))
        self.assertIn(f'<link rel="canonical" href="{DEFAULT_SITE_URL}/">', self.page)
        self.assertIn('hreflang="x-default"', self.page)

    def test_social_cards_point_at_absolute_image(self):
        self.assertIn(f'<meta property="og:image" content="{DEFAULT_SITE_URL}/og-image.jpg">', self.page)
        self.assertIn('<meta name="twitter:card" content="summary_large_image">', self.page)
        self.assertIn('<meta property="og:locale" content="he_IL">', self.page)

    def test_structured_data_is_valid_json_for_a_free_video_game(self):
        raw = re.search(r'<script type="application/ld\+json">\s*(.*?)\s*</script>', self.page, re.S).group(1)
        graph = json.loads(raw)["@graph"]
        game = next(item for item in graph if item["@type"] == "VideoGame")
        self.assertEqual(game["offers"]["price"], "0")
        self.assertTrue(game["isAccessibleForFree"])
        self.assertEqual(game["url"], DEFAULT_SITE_URL + "/")

    def test_crawlable_text_and_guide_links_exist_in_the_body(self):
        self.assertIn('<main id="wf-seo"', self.page)
        self.assertIn("<h1>World Fight", self.page)
        self.assertIn('href="about/"', self.page)
        self.assertIn("<noscript>", self.page)
        self.assertLess(self.page.index('id="worldFightDisclaimer"'), self.page.index('<script src="index.js">'))

    def test_patching_twice_keeps_one_of_everything(self):
        patch(self.out / "index.html", CONFIG)
        again = (self.out / "index.html").read_text(encoding="utf-8")
        self.assertEqual(again.count("<title>"), 1)
        self.assertEqual(again.count('rel="canonical"'), 1)
        self.assertEqual(again.count('id="wf-seo"'), 1)

    def test_static_site_files_are_published(self):
        for name in ("robots.txt", "sitemap.xml", "CNAME", "404.html", "favicon.ico", "icon-192.png", "icon-512.png", "icon-512-maskable.png", "apple-touch-icon.png", "og-image.jpg", "about/index.html", "en/index.html", "google5ee28a7b3ea4abc3.html"):
            self.assertTrue((self.out / name).is_file(), name)
        self.assertEqual((self.out / "CNAME").read_text(encoding="utf-8").strip(), "israel-election-fight.online")
        sitemap = (self.out / "sitemap.xml").read_text(encoding="utf-8")
        self.assertNotIn("__BUILD_DATE__", sitemap)
        for path in ("/", "/about/", "/en/"):
            self.assertIn(f"<loc>{DEFAULT_SITE_URL}{path}</loc>", sitemap)
        robots = (self.out / "robots.txt").read_text(encoding="utf-8")
        self.assertIn(f"Sitemap: {DEFAULT_SITE_URL}/sitemap.xml", robots)
        self.assertNotIn("stats-", robots + sitemap, "the private dashboard path must never be advertised")

    def test_manifest_icons_exist(self):
        manifest = json.loads((self.out / "manifest.webmanifest").read_text(encoding="utf-8"))
        self.assertEqual(manifest["lang"], "he")
        for icon in manifest["icons"]:
            if icon["src"].startswith("index."):
                continue  # generated by the Godot export itself
            self.assertTrue((self.out / icon["src"]).is_file(), icon["src"])
        self.assertTrue(any(icon.get("purpose") == "maskable" for icon in manifest["icons"]))

    def test_guide_pages_are_indexable_and_cross_linked(self):
        about = (STATIC_DIR / "about" / "index.html").read_text(encoding="utf-8")
        english = (STATIC_DIR / "en" / "index.html").read_text(encoding="utf-8")
        for page, own in ((about, "/about/"), (english, "/en/")):
            self.assertIn(f'rel="canonical" href="{DEFAULT_SITE_URL}{own}"', page)
            self.assertNotIn("noindex", page)
            self.assertIn("<h1>", page)
            self.assertEqual(len(re.findall(r"<h1>", page)), 1)
        self.assertIn('hreflang="en"', about)
        self.assertIn('hreflang="he"', english)
        self.assertIn('lang="en"', english)

    def test_configured_site_url_is_used_everywhere(self):
        with TemporaryDirectory() as other:
            target = Path(other)
            (target / "index.html").write_text(SHELL, encoding="utf-8")
            patch(target / "index.html", dict(CONFIG, site_url="https://example.test"))
            page = (target / "index.html").read_text(encoding="utf-8")
            self.assertIn('rel="canonical" href="https://example.test/"', page)
            self.assertIn("<loc>https://example.test/about/</loc>", (target / "sitemap.xml").read_text(encoding="utf-8"))

    def test_site_config_declares_the_custom_domain(self):
        self.assertEqual(load_site_config()["site_url"], DEFAULT_SITE_URL)


if __name__ == "__main__":
    unittest.main()
